
pi2:
	rsync -rv -e'ssh -J remote.moe' ./ pi@smartmanualstationdanfoss.remote.moe:SmartManualStation
pi2clean:
	rsync -rv -e 'ssh -J remote.moe' --delete ./ pi@smartmanualstationdanfoss.remote.moe:SmartManualStation
